######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 1 21:49:11 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Data.h RankVerifyDialog.h
FORMS += RankVerify.ui
SOURCES += RankVerify.cpp RankVerifyDialog.cpp WinOrientDoc.cpp
